### ISSUE TITLE
[UserStory] Switching from Ant to Gradle 

### ISSUE THREAD

**Issue by wavypng** [MetroCS/redistricting#112]
# User Story
### Essential components
- [x] Title describes the story
- [ ] Stakeholder type is identified
- [x] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  developer  
**I want**  the program to run on Gradle instead of Ant
**so that**  the developers don't have problems with ant as our whole team had issues with ant as a local problem and so did other teams.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ The program accurately working on a new gradle build environment. 

## Dependencies
N/A

**Comment by jody** [comment]
Please provide specifics regarding the problems driving this user story.

Does this concern a lack of instructions for configuring the build environment on a particular platorm?
Is there an issue with the build environment itself?

At present, there are working Ant development environments for this project on GNU/Linux, BSD Unix, Solaris Unix, macOS, and Windows platforms.

**Comment by jody** [comment]
> As a developer

Is this intentionally only a subset of the _maintainer_ stakeholder type?
Might this change also affect other stakeholders?

**Comment by jody** [comment]
>I want the program to run on Gradle instead of Ant

Is there a way for Gradle to co-exist with Ant?
If so, can this user story be modified to "Gradle in addition to Ant"?

**Comment by jody** [comment]
>so that the developers don't have problems with ant as our whole team had issues with ant as a local problem and so did other teams.

Please articulate what problems are being addressed by this user story.
Otherwise, this appears to be a specific solution without a particular problem.
Why wouldn't other solutions be as or more appropriate than the one proffered?

The current statement of the goal _(developers don't have problems with ant)_ may be trivially addressed by simply removing (or ignoring) build.xml and relying on the individual developers to use whichever build process best suits them.

**Comment by jody** [comment]
Incomplete. No response in 29 days. Closing issue.
