### ISSUE TITLE
[UserStory] Add test for SnakingLocationComparer(Comparator<Location>{...}

### ISSUE THREAD

**Issue by Julian3390** [MetroCS/redistricting#128]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  maintainer
**I want**  an effective test method for the SnakingLocationComparer(compare) constructor
**so that** the public method in SnakingLocationComparer has a corresponding test. 

Supporting Information

At present there is only one public method:

https://github.com/MetroCS/redistricting/blob/435fe38103a255169262be714609fc30df04dd01/src/swdmt/redistricting/SnakingLocationComparer.java#L25-L47

## Acceptance Criteria
- At least one test method exists in compare constructor.
- All executable lines of the compare constructor are exercised during automated unit testing.

**Comment by jody** [comment]
Please use links to the actual source so that we have a direct link to the code that you are referring to.

The comment is confusing. The [SnakingLocationComparer](https://github.com/MetroCS/redistricting/blob/master/src/swdmt/redistricting/SnakingLocationComparer.java) class doesn't have an explicit constructor, thus only the Java default constructor exists for that class, `public SnakingLocationComparer()`.

**Comment by jody** [comment]
Incomplete. No response in 16 days. Closing issue.
