### ISSUE TITLE
[UserStory] StarGenerator invalid parameter value handling

### ISSUE THREAD

**Issue by ColinLouis95** [MetroCS/redistricting#189]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a** Programmer
**I want**  invalid inputs for the StarGenerator.java generatePattern method to throw exceptions
**so that** I know an invalid parameter value was passed instead of a stack overflow error. 

## Acceptance Criteria
* _When an invalid input is given to the generatePattern method it throws an invalidInputException error._
* _When an invalid input is given, the generatePattern method does not throw a stack overflow error._

## Supporting Information
_(Currently method throws stack overflow error if given values of 0 or less.)_

**Comment by jody** [comment]
This User Story should describe the problem to be addressed rather than prescribing a specific solution. For example, why is throwing an exception the only appropriate way to handle specific parameter values?

Likewise, why is "invalidInputException" the proper exception to be thrown? Why not "InvalidParameterException", "IllegalArgumentException", or some other exception? The acceptance criteria appear to be prescribing a particular solution rather than characteristics of any acceptable solution.

**Comment by jody** [comment]
No response in over 30 days.
